name: HLint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: domdere/haskell-lint-action@v1.0.2
    env:	
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
